### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by yinnianlong** [labplus-cn/mPython#18]
/home/yin/esp1/esp-idf/esp-idf/components/bootloader_support/src/bootloader_common.c: In function 'bootloader_common_get_partition_description':
/home/yin/esp1/esp-idf/esp-idf/components/log/include/esp_log.h:117:26: error: 'CONFIG_LOG_BOOTLOADER_LEVEL' undeclared (first use in this function)
 #define LOG_LOCAL_LEVEL  CONFIG_LOG_BOOTLOADER_LEVEL

**Comment by lgnativs** [comment]
ESP-IDF的helloworld能否编译成功?

**Comment by yinnianlong** [comment]
非常感谢您的回复&nbsp; 我编译helloworld和micropython源码都可以编译生成bin




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZhangKaihua"<notifications@github.com&gt;; 
发送时间: 2019年10月7日(星期一) 上午10:42
收件人: "labplus-cn/mPython"<mPython@noreply.github.com&gt;; 
抄送: "流云"<106312845@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [labplus-cn/mPython] 编译报错 (#18)




ESP-IDF的helloworld能否编译成功?

**Comment by yinnianlong** [comment]
请问这个开源项目有组织吗？我如何找到组织的联系方式一起学习交流
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZhangKaihua"<notifications@github.com&gt;; 
发送时间: 2019年10月7日(星期一) 上午10:42
收件人: "labplus-cn/mPython"<mPython@noreply.github.com&gt;; 
抄送: "流云"<106312845@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [labplus-cn/mPython] 编译报错 (#18)




ESP-IDF的helloworld能否编译成功?

**Comment by lgnativs** [comment]
可以直接在这里提问的.
你编译的源码有修改吗?我们这里编译都是没有问题的.

**Comment by yinnianlong** [comment]
非常感谢！

我又重试了&nbsp;还是有错误

1 编译micropython&nbsp;正常生成bin&nbsp;无错误

2 编译mPython

3 提示IDF分支不一致

Current git hash:&nbsp;&nbsp; 6ccb4cf5b7d1fdddb8c2492f9cbc926abaf230df

Supported git hash: 5c88c5996dbde6208e3bec05abc21ff6cd822d26

4 切换分支到5c88c5996dbde6208e3bec05abc21ff6cd822d26

5 再编译报如下错误

/home/yin/esp1/esp-idf/esp-idf/components/bootloader_support/src/bootloader_flash.c: In function 'bootloader_mmap':

/home/yin/esp1/esp-idf/esp-idf/components/log/include/esp_log.h:117:26: error: 'CONFIG_LOG_BOOTLOADER_LEVEL' undeclared (first use in this function)

 

&nbsp;#define LOG_LOCAL_LEVEL&nbsp; CONFIG_LOG_BOOTLOADER_LEVEL




图片见附件







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhangKaihua"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月7日(星期一) 中午11:39
收件人:&nbsp;"labplus-cn/mPython"<mPython@noreply.github.com&gt;;
抄送:&nbsp;"流云"<106312845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [labplus-cn/mPython] 编译报错 (#18)




可以直接在这里提问的.
 你编译的源码有修改吗?我们这里编译都是没有问题的.

**Comment by lgnativs** [comment]
建议清空ESP-IDF文件夹,再checkout到匹配的版本

**Comment by yinnianlong** [comment]
好的&nbsp;我试试&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZhangKaihua"<notifications@github.com&gt;; 
发送时间: 2019年10月7日(星期一) 下午3:21
收件人: "labplus-cn/mPython"<mPython@noreply.github.com&gt;; 
抄送: "流云"<106312845@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [labplus-cn/mPython] 编译报错 (#18)




建议清空ESP-IDF文件夹,再checkout到匹配的版本

**Comment by yinnianlong** [comment]
按照port/ESP32/makefile文件里的描述&nbsp;我克隆5c88c5996dbde6208e3bec05abc21ff6cd822d26这个分支&nbsp;说未发现
# the git hash of the currently supported ESP IDF version
ESPIDF_SUPHASH := 5c88c5996dbde6208e3bec05abc21ff6cd822d26



root@yin-virtual-machine:/home/yin# cd '/home/yin/esp1'&nbsp;
root@yin-virtual-machine:/home/yin/esp1# git clone -b 5c88c5996dbde6208e3bec05abc21ff6cd822d26 https://github.com/espressif/esp-idf.git
正克隆到 'esp-idf'...
fatal: 远程分支 5c88c5996dbde6208e3bec05abc21ff6cd822d26 在上游 origin 未发现
root@yin-virtual-machine:/home/yin/esp1#&nbsp;







------------------ 原始邮件 ------------------
发件人: &nbsp;"ZhangKaihua"<notifications@github.com&gt;;
发送时间: &nbsp;2019年10月7日(星期一)下午3:21
收件人: &nbsp;"labplus-cn/mPython"<mPython@noreply.github.com&gt;;
抄送: &nbsp;"流云"<106312845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: &nbsp;Re: [labplus-cn/mPython]编译报错(#18)




建议清空ESP-IDF文件夹,再checkout到匹配的版本

**Comment by yinnianlong** [comment]
谢谢 问题已解决是我的IDF下载有问题



---原始邮件---
发件人: "ZhangKaihua"<notifications@github.com&gt;
发送时间: 2019年10月7日(星期一) 中午11:39
收件人: "labplus-cn/mPython"<mPython@noreply.github.com&gt;;
抄送: "yinnianlong"<106312845@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [labplus-cn/mPython] 编译报错 (#18)



可以直接在这里提问的.
 你编译的源码有修改吗?我们这里编译都是没有问题的.
