### ISSUE TITLE
bme280芯片的气压值无法单独输出

### ISSUE THREAD

**Issue by 13682374459** [labplus-cn/mpython#23]
**描述错误**
人工智能交互实验箱的bme280芯片，单独输出气压值显示note，如果把湿度或温度一起显示就不会。人工智能交互实验箱的bme280芯片，单独输出气压值显示note，如果把湿度或温度一起显示就不会。

**复现方法**
1. 单独输出bme280芯片的气压值api，
from mpython import *
print(bme280.pressure())
打印为note

2. 输出bme280芯片的气压值api，湿度api和温度api
from mpython import *
print(bme280.pressure())
print(bme280.humidity())
print(bme280.temperature())
打印为数字

**Comment by diskman88** [comment]
原因：有两个参数需通过读取温度值确定。解决办法：修改驱动。问题解决在提交：[ae976](https://github.com/labplus-cn/mpython/commit/ae976b48a49190ce48288f3a7d4b11820064217a)

**Comment by diskman88** [comment]
> **描述错误**
> 人工智能交互实验箱的bme280芯片，单独输出气压值显示note，如果把湿度或温度一起显示就不会。人工智能交互实验箱的bme280芯片，单独输出气压值显示note，如果把湿度或温度一起显示就不会。
> 
> **复现方法**
> 
> 1. 单独输出bme280芯片的气压值api，
>    from mpython import *
>    print(bme280.pressure())
>    打印为note
> 2. 输出bme280芯片的气压值api，湿度api和温度api
>    from mpython import *
>    print(bme280.pressure())
>    print(bme280.humidity())
>    print(bme280.temperature())
>    打印为数字

原因：tFine参数需通过读取温度值确定。解决办法：修改驱动。问题解决在提交：[ae976](https://github.com/labplus-cn/mpython/commit/ae976b48a49190ce48288f3a7d4b11820064217a)
