### ISSUE TITLE
[掌中宝]喇叭异响

### ISSUE THREAD

**Issue by 13682374459** [labplus-cn/mpython#24]
**掌中宝**
**描述问题**
掌中宝的oled显示麦克风大小或者光线时，会发出滴滴的声音，喇叭传出来的，把扩展板电源关了就不会有了。

**复现方法**
掌中宝通过oled屏幕显示光线或声音(扩展板要打开电源)
from mpython import *
while True:
    oled.fill(0)
    oled.DispChar((str(light.read())), 0, 0, 1)
    oled.DispChar((str(sound.read())), 0, 16, 1)
    oled.show()

**Comment by diskman88** [comment]
原因：esp-idf固件bug引起。修复方法：运行mpython/idf-patch/idf-patch.sh，给esp-idf打补丁。然后重新编译固件。
