### ISSUE TITLE
[人工智能交互实验箱]麦克风1与麦克风2检测声音的范围不同

### ISSUE THREAD

**Issue by lgnativs** [labplus-cn/mpython#25]
**人工智能交互实验箱**
**描述问题**
实验箱麦克风1与麦克风2检测声音的范围不同。语音识别只能右边可以用

**复现方法**
掌中宝通过oled屏幕显示光线或声音(扩展板要打开电源)
from mpython import *
sound.init()
while True:
    print(sound.read())

**Comment by diskman88** [comment]
双麦克风设计的意图是实现左右声道录音。做声音触发器用时，只需一个声道就可以了。做录音功能时实云端语音服务时，云端一般也只需单声道数据，所以目前的应用都只用了右声道。后续可开发一些左右声道都利用的应用，实现更好的录音效果。
