### ISSUE TITLE
编译master分支最新代码，不能正确导入mpython

### ISSUE THREAD

**Issue by ouki-wang** [labplus-cn/mPython#8]
出现引脚不用错误
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 25, in <module>
ValueError: invalid pin

**Comment by lgnativs** [comment]
方便贴上的出现错误的python代码吗?

**Comment by ouki-wang** [comment]
我猜测是你内部pin重新map后，mpython.py中的pin还是使用的以前的

**Comment by lgnativs** [comment]
已经更新,还原原本的Pin定义[https://github.com/labplus-cn/mPython/commit/44e6f7c1a48cda1239385eba99a9061a0940b883](url)
